const {spawn}=require('child_process'),os=require('os'),fs=require('fs'),path=require('path'),assert=require('assert');
const {io}=require('socket.io-client'),CK=require('./public/shared.js');
const arrivals=CK.timeline({balls:[{striker:'Nikhil',nonStriker:'Avi'},{striker:'Nikhil',nonStriker:'Avi',w:{type:'caught'}},{striker:'Rohan',nonStriker:'Avi'}]});
assert.strictEqual(arrivals[2].arrival,'Rohan','timeline identifies a new batter after a wicket');
assert.ok(!CK.text({bowler:'Mishra',striker:'Nikhil',w:{type:'caught',catcher:'Kohli',fielder:'Kohli'}}).includes('fielder Kohli'),'catcher name is not duplicated');
assert.strictEqual(CK.chip({t:'dead',r:0}),'DB','dead ball has a distinct history chip');
assert.strictEqual(CK.text({t:'dead',r:0,bowler:'Mishra',striker:'Nikhil'}),'Mishra to Nikhil, dead ball','dead ball is not shown as a dot delivery');
const PORT=31000+Math.floor(Math.random()*20000),B='http://localhost:'+PORT,dir=fs.mkdtempSync(path.join(os.tmpdir(),'sb-'));
const srv=spawn('node',['server.js'],{env:{...process.env,PORT,ADMIN_PASSWORD:'pw',DATA_DIR:dir},stdio:'inherit'});
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const waitForServer=async()=>{const until=Date.now()+10000;while(Date.now()<until){try{const r=await fetch(B+'/api/matches');if(r.ok)return}catch{}await sleep(100)}throw new Error('Test server did not become ready')};
const call=async(p,method='GET',body,t)=>{const r=await fetch(B+p,{method,headers:{'Content-Type':'application/json',...(t?{'x-token':t}:{})},body:body?JSON.stringify(body):undefined});return{status:r.status,body:await r.json()}};
(async()=>{let ok=false;try{await waitForServer();
 for(const file of ['/admin.js','/charts.js','/fx.js','/add-match.html'])assert.strictEqual((await fetch(B+file)).status,200,`${file} must be served`);
 assert.strictEqual((await call('/api/login','POST',{password:'bad'})).status,401);
 const t=(await call('/api/login','POST',{password:'pw'})).body.token;
 assert.strictEqual((await fetch(B+'/api/session',{headers:{'x-token':t}})).status,200,'valid session is accepted');
 assert.strictEqual((await fetch(B+'/api/session',{headers:{'x-token':'stale-token'}})).status,401,'stale session is rejected');
 assert.strictEqual((await call('/api/matches','POST',{teamA:'A',teamB:'B'})).status,401,'create needs login');
 const sock=io(B),got=[];sock.on('match',m=>got.push(m));await sleep(300);
 const m=(await call('/api/matches','POST',{teamA:'Tigers',teamB:'Lions',overs:2},t)).body,u='/api/matches/'+m.id;
 assert.strictEqual(m.toss.status,'idle','new matches begin with an idle toss');
 const tossing=await call(u+'/toss/start','POST',{},t);
 assert.strictEqual(tossing.status,200,'scorer can start the toss');
 assert.strictEqual(tossing.body.toss.status,'flipping','toss-in-progress is persisted and published');
 const toss=(await call(u+'/toss','POST',{wonBy:'Tigers',decision:'batting'},t)).body;
 assert.deepStrictEqual(toss.toss,{status:'announced',wonBy:'Tigers',decision:'batting',announced:true},'toss result ends the flip and is stored');
 assert.strictEqual((await call(u+'/ball','POST',{r:1},t)).status,400,'ball before innings');
 for(const name of ['Nikhil','Avi','Rohan'])assert.strictEqual((await call(u+'/squad','POST',{side:'A',name},t)).status,200,'batting roster member added');
 for(const name of ['Rohit','Kohli','Mishra','Keeper'])assert.strictEqual((await call(u+'/squad','POST',{side:'B',name},t)).status,200,'bowling roster member added');
 await call(u+'/innings','POST',{},t);
 assert.strictEqual((await call(u+'/break','POST',{paused:true},t)).body.break,true,'scorer can start a match break');
 assert.strictEqual((await call(u+'/ball','POST',{r:1},t)).status,400,'scoring is blocked during a break');
 assert.strictEqual((await call(u+'/break','POST',{paused:false},t)).body.break,false,'scorer can resume play');
 for(const b of [{r:1},{r:4},{r:0,t:'dead'},{r:1,t:'wd'},{r:0},{r:6},{r:1,t:'lb'}])await call(u+'/ball','POST',b,t);
 assert.strictEqual((await call(u+'/ball','POST',{r:0,w:{type:'caught',catcher:'Nikhil'}},t)).status,400,'dismissal fielder must belong to bowling team');
 const wicket=(await call(u+'/ball','POST',{r:0,w:{type:'caught',catcher:'Kohli',fielder:'Kohli',outPlayer:'Nikhil',newBatter:'Rohan'},striker:'Nikhil',nonStriker:'Avi',bowler:'Mishra',nextStriker:'Rohan',nextNonStriker:'Avi'},t)).body;
 assert.strictEqual(wicket.current.striker,'Rohan','replacement takes the dismissed striker position');
 const last = wicket.innings[0].balls[wicket.innings[0].balls.length-1];
 assert.ok(last.w&&last.w.type==='caught'&&last.outPlayer==='Nikhil'&&last.newBatter==='Rohan','dismissed and replacement players are saved');
 await sleep(300);let s=CK.summarize(got[got.length-1])[0];
 assert.deepStrictEqual([s.runs,s.wkts,s.balls,s.overs],[13,1,6,'1.0'],'score after dead ball, extras, and a wicket');
 await call(u+'/undo','POST',{},t);await sleep(200);s=CK.summarize(got[got.length-1])[0];
 assert.deepStrictEqual([s.runs,s.balls],[13,5],'undo restores prior score');
 assert.strictEqual((await call(u+'/squad','POST',{side:'B',name:'Nikhil'},t)).status,400,'duplicate squad names across teams rejected');
 await call(u+'/finish','POST',{result:'Lions won'},t);
 const all=(await call('/api/matches')).body;assert.strictEqual(all[0].status,'completed');assert.strictEqual(all[0].winner,'Lions','manual winner can be shown on match cards');
 assert.ok(fs.readFileSync(path.join(dir,'data.json'),'utf8').includes(m.id),'saved to disk');
 const decided=(await call('/api/matches','POST',{teamA:'Red',teamB:'Green',overs:1},t)).body,du='/api/matches/'+decided.id;
 await call(du+'/innings','POST',{team:'Red'},t);for(let k=0;k<6;k++)await call(du+'/ball','POST',{r:0},t);
 await call(du+'/innings','POST',{},t);await call(du+'/ball','POST',{r:1},t);
 const final=(await call(du+'/finish','POST',{},t)).body;assert.strictEqual(final.winner,'Green','winner is calculated from innings scores');assert.strictEqual(final.result,'Green won by 10 wickets','automatic result is available for the finished banner');
 const tossChoice=(await call('/api/matches','POST',{teamA:'Eagles',teamB:'Falcons',overs:5},t)).body,tu='/api/matches/'+tossChoice.id;
 await call(tu+'/toss/start','POST',{},t);await call(tu+'/toss','POST',{wonBy:'Falcons',decision:'batting'},t);
 const tossInnings=(await call(tu+'/innings','POST',{},t)).body;assert.strictEqual(tossInnings.innings[0].team,'Falcons','team B bats first when it wins the toss and chooses batting');
 console.log('All tests passed');ok=true;sock.close()}catch(e){console.error('TEST FAILED:',e.message)}srv.kill();process.exit(ok?0:1)})();
