const {spawn}=require('child_process'),os=require('os'),fs=require('fs'),path=require('path'),assert=require('assert');
const {io}=require('socket.io-client'),CK=require('./public/shared.js');
const PORT=3101,B='http://localhost:'+PORT,dir=fs.mkdtempSync(path.join(os.tmpdir(),'sb-'));
const srv=spawn('node',['server.js'],{env:{...process.env,PORT,ADMIN_PASSWORD:'pw',DATA_DIR:dir},stdio:'inherit'});
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const call=async(p,method='GET',body,t)=>{const r=await fetch(B+p,{method,headers:{'Content-Type':'application/json',...(t?{'x-token':t}:{})},body:body?JSON.stringify(body):undefined});return{status:r.status,body:await r.json()}};
(async()=>{let ok=false;try{await sleep(800);
 for(const file of ['/admin.js','/charts.js','/fx.js','/add-match.html'])assert.strictEqual((await fetch(B+file)).status,200,`${file} must be served`);
 assert.strictEqual((await call('/api/login','POST',{password:'bad'})).status,401);
 const t=(await call('/api/login','POST',{password:'pw'})).body.token;
 assert.strictEqual((await fetch(B+'/api/session',{headers:{'x-token':t}})).status,200,'valid session is accepted');
 assert.strictEqual((await fetch(B+'/api/session',{headers:{'x-token':'stale-token'}})).status,401,'stale session is rejected');
 assert.strictEqual((await call('/api/matches','POST',{teamA:'A',teamB:'B'})).status,401,'create needs login');
 const sock=io(B),got=[];sock.on('match',m=>got.push(m));await sleep(300);
 const m=(await call('/api/matches','POST',{teamA:'Tigers',teamB:'Lions',overs:2},t)).body,u='/api/matches/'+m.id;
 assert.strictEqual((await call(u+'/ball','POST',{r:1},t)).status,400,'ball before innings');
 await call(u+'/innings','POST',{},t);
 for(const b of [{r:1},{r:4},{r:1,t:'wd'},{r:0,w:true},{r:6}])await call(u+'/ball','POST',b,t);
 await sleep(300);let s=CK.summarize(got[got.length-1])[0];
 assert.deepStrictEqual([s.runs,s.wkts,s.balls,s.overs],[12,1,4,'0.4'],'score after 5 events');
 await call(u+'/undo','POST',{},t);await sleep(200);s=CK.summarize(got[got.length-1])[0];
 assert.deepStrictEqual([s.runs,s.balls],[6,3],'undo works');
 await call(u+'/innings','POST',{},t);assert.strictEqual((await call(u+'/innings','POST',{},t)).status,400,'max 2 innings');
 const toss=(await call(u+'/toss','POST',{wonBy:'Tigers',decision:'batting'},t)).body;
 assert.deepStrictEqual(toss.toss,{wonBy:'Tigers',decision:'batting',announced:true},'toss info is stored');
 const dup=(await call(u+'/squad','POST',{side:'A',name:'Nikhil'},t));
 assert.strictEqual(dup.status,200,'first squad entry ok');
 assert.strictEqual((await call(u+'/squad','POST',{side:'B',name:'Nikhil'},t)).status,400,'duplicate squad names across teams rejected');
 const wicket=(await call(u+'/ball','POST',{w:{type:'caught',fielder:'Rohit',catcher:'Kohli'},striker:'Nikhil',nonStriker:'Avi',bowler:'Mishra'},t)).body;
 assert.strictEqual(wicket.current.striker,'Nikhil','current striker carries forward');
 const last = wicket.innings[0].balls[wicket.innings[0].balls.length-1];
 assert.ok(last.w && last.w.type==='caught','wicket details are saved');
 await call(u+'/finish','POST',{result:'Lions won'},t);
 const all=(await call('/api/matches')).body;assert.strictEqual(all[0].status,'completed');
 assert.ok(fs.readFileSync(path.join(dir,'data.json'),'utf8').includes(m.id),'saved to disk');
 console.log('All tests passed');ok=true;sock.close()}catch(e){console.error('TEST FAILED:',e.message)}srv.kill();process.exit(ok?0:1)})();
